services:
  - type: web
    name: butaca-cero
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./docker/django/Dockerfile
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: butaca-cero-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          name: butaca-cero
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: DJANGO_SERVE_MEDIA
        value: "True"

databases:
  - name: butaca-cero-db
    plan: free
    postgresMajorVersion: "16"
