# Generated by Django 6.1.1 on 2026-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_compraasiento_reservaasiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraasiento',
            name='utilizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
