# Generated by Django 6.1.1 on 2026-09-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ANIMACION', 'Animación'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('CIENCIA_FICCION', 'Ciencia ficción'), ('SUSPENSO', 'Suspenso'), ('ROMANCE', 'Romance'), ('DOCUMENTAL', 'Documental'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical')], max_length=20)),
                ('clasificacion', models.CharField(choices=[('ATP', 'ATP - Apta para todo público'), ('+13', '+13 años'), ('+16', '+16 años'), ('+18', '+18 años')], max_length=5)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración de la película en minutos')),
                ('imagen', models.ImageField(upload_to='peliculas/')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['titulo'],
            },
        ),
    ]
