# Generated by Django 6.1.1 on 2026-09-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='capacidad',
        ),
    ]
