# Generated by Django 6.1.1 on 2026-09-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='rooms.sala')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['sala'],
            },
        ),
    ]
