# Generated by Django 6.1.1 on 2026-09-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_remove_sala_capacidad'),
        ('seat_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.sala')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seat_types.seattype')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['sala'],
            },
        ),
    ]
