# Generated by Django 6.1.1 on 2026-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.CharField(max_length=7)),
                ('icono', models.ImageField(blank=True, upload_to='seat_icons/')),
            ],
            options={
                'verbose_name': 'Tipo de Asiento',
                'verbose_name_plural': 'Tipos de Asientos',
            },
        ),
    ]
